export interface JobSkillMapping {
  job: string;
  skills: string[];
}

export const JOBS_WITH_SKILLS: Record<string, string[]> = {
  "Frontend Developer": [
    "React",
    "Next.js",
    "TypeScript",
    "Tailwind CSS",
    "JavaScript",
    "HTML/CSS",
    "Redux",
    "Zustand",
    "Vue.js",
  ],
  "Backend Developer": [
    "Node.js",
    "Express.js",
    "Python",
    "Django",
    "PostgreSQL",
    "MongoDB",
    "REST API",
    "GraphQL",
    "Docker",
    "Redis",
  ],
  "Full Stack Developer": [
    "React",
    "Next.js",
    "Node.js",
    "TypeScript",
    "Tailwind CSS",
    "PostgreSQL",
    "MongoDB",
    "REST API",
    "Git",
  ],
  "Mobile Developer": [
    "React Native",
    "Flutter",
    "Swift",
    "Kotlin",
    "iOS",
    "Android",
    "REST API",
    "Firebase",
  ],
  "Software Engineer": [
    "Algorithms",
    "Data Structures",
    "System Design",
    "Git",
    "OOP",
    "C++",
    "Java",
    "Python",
  ],
  "DevOps Engineer": [
    "Docker",
    "Kubernetes",
    "AWS",
    "CI/CD",
    "Linux",
    "Terraform",
    "Bash",
    "Nginx",
  ],
  "Cloud Engineer": [
    "AWS",
    "Google Cloud",
    "Azure",
    "Terraform",
    "Docker",
    "Serverless",
    "Networking",
  ],
  "AI Engineer": [
    "Python",
    "PyTorch",
    "TensorFlow",
    "OpenAI API",
    "LangChain",
    "Machine Learning",
    "LLMs",
  ],
  "Machine Learning Engineer": [
    "Python",
    "Scikit-Learn",
    "TensorFlow",
    "PyTorch",
    "Pandas",
    "NumPy",
    "Data Preprocessing",
  ],
  "Data Scientist": [
    "Python",
    "R",
    "SQL",
    "Data Analysis",
    "Pandas",
    "Matplotlib",
    "Statistics",
    "Machine Learning",
  ],
  "Data Analyst": [
    "SQL",
    "Excel",
    "PowerBI",
    "Tableau",
    "Python",
    "Data Visualization",
  ],
  "Cybersecurity Specialist": [
    "Network Security",
    "Penetration Testing",
    "Ethical Hacking",
    "Cryptography",
    "Linux",
    "SOC",
  ],
  "QA Engineer": [
    "Manual Testing",
    "Automation Testing",
    "Jest",
    "Cypress",
    "Selenium",
    "Postman",
    "Bug Tracking",
  ],
  "Automation Tester": [
    "Cypress",
    "Playwright",
    "Selenium",
    "JavaScript/TypeScript",
    "CI/CD",
    "Jest",
  ],
  "UI/UX Designer": [
    "Figma",
    "User Research",
    "Wireframing",
    "Prototyping",
    "Design Systems",
    "Adobe XD",
  ],
  "Product Designer": [
    "Figma",
    "Design Thinking",
    "User Journeys",
    "UI Design",
    "Prototyping",
  ],
  "Graphic Designer": [
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Branding",
    "Typography",
    "Canva",
  ],
  "Motion Designer": [
    "After Effects",
    "Cinema 4D",
    "Blender",
    "Animation",
    "Premiere Pro",
  ],
  "Product Manager": [
    "Agile/Scrum",
    "Product Roadmap",
    "User Stories",
    "Analytics",
    "Jira",
    "Market Research",
  ],
  "Project Manager": [
    "Jira",
    "Agile",
    "Scrum",
    "Risk Management",
    "Asana",
    "Trello",
  ],
  "Scrum Master": ["Scrum", "Agile", "Kanban", "Facilitation", "Jira"],
  "Business Analyst": [
    "Requirements Gathering",
    "SQL",
    "BPMN",
    "Data Analysis",
    "Excel",
  ],
  "Digital Marketer": [
    "SMM",
    "SEO",
    "Google Ads",
    "Facebook Ads",
    "Content Marketing",
    "Email Marketing",
  ],
  "SEO Specialist": [
    "Keyword Research",
    "On-Page SEO",
    "Off-Page SEO",
    "Google Analytics",
    "Ahrefs",
    "Semrush",
  ],
  "Content Creator": [
    "Video Editing",
    "Copywriting",
    "Storytelling",
    "Social Media",
    "Canva",
  ],
  Copywriter: [
    "Copywriting",
    "SEO Writing",
    "Content Strategy",
    "Proofreading",
    "Creative Writing",
  ],
  "Sales Manager": [
    "B2B Sales",
    "Lead Generation",
    "CRM",
    "Negotiation",
    "Cold Calling",
  ],
  "HR Manager": [
    "Recruiting",
    "Employee Relations",
    "HR Policies",
    "Onboarding",
    "Performance Management",
  ],
  Recruiter: [
    "Sourcing",
    "Interviewing",
    "LinkedIn Recruiter",
    "Talent Acquisition",
  ],
  "Customer Support Specialist": [
    "Zendesk",
    "Communication",
    "Problem Solving",
    "CRM",
    "Helpdesk",
  ],
  Entrepreneur: [
    "Business Strategy",
    "Fundraising",
    "Product Management",
    "Leadership",
    "Marketing",
  ],
  Student: [
    "Time Management",
    "Research",
    "Critical Thinking",
    "Problem Solving",
  ],
  Teacher: ["Curriculum Design", "Public Speaking", "Mentorship", "E-Learning"],
  Accountant: ["Financial Accounting", "Excel", "Taxation", "Auditing", "1C"],
  Consultant: [
    "Strategic Planning",
    "Problem Solving",
    "Data Analysis",
    "Presentation Skills",
  ],
  Other: [
    "Communication",
    "Problem Solving",
    "Teamwork",
    "Management",
    "Project Planning",
  ],
};

export const JOBS_LIST = Object.keys(JOBS_WITH_SKILLS);
