import type { Metadata } from "next";
import dynamic from "next/dynamic";
const Navbar = dynamic(() => import("@/components/shared/navbar"));
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <Navbar />
      <div className="border border-white w-full max-w-370 mx-auto">
        {children}
      </div>
    </main>
  );
}
